In [1]:
import numpy as np
import pandas as pd
import calendar
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report

In [2]:
# preprocess=pd.read_csv('preprocess.csv', engine='python',index_col="arrival_date")
train=pd.read_csv('preprocess_all/preprocess_train_num_all.csv', engine='python',index_col="arrival_date")
# train=train.drop(["label"],axis=1)
train

hotel_Resort  hotel_City   lead_time  arrival_date_week_number  \
arrival_date                                                                   
2015/7/1                38          65  190.291262                        27   
2015/7/2                35           1   69.944444                        27   
2015/7/3                27          10   65.378378                        27   
2015/7/4                36           9  120.777778                        27   
2015/7/5                37           0   75.378378                        28   
...                    ...         ...         ...                       ...   
2017/3/27               25          89   96.368421                        13   
2017/3/28               33          34   52.537313                        13   
2017/3/29               51          79   41.130769                        13   
2017/3/30               51          73   59.137097                        13   
2017/3/31               64          76   58.053846                        13   

              stays_nights    adults  children    babies  meal_BB  meal_FB  \
arrival_date                                                                 
2015/7/1          3.048544  1.805825  0.019417  0.000000       35        1   
2015/7/2          5.694444  1.972222  0.055556  0.000000       27        1   
2015/7/3          4.324324  2.000000  0.081081  0.000000       22        0   
2015/7/4          5.311111  1.977778  0.111111  0.044444       37        1   
2015/7/5          6.108108  1.945946  0.216216  0.000000       26        0   
...                    ...       ...       ...       ...      ...      ...   
2017/3/27         2.982456  1.842105  0.000000  0.000000       99        0   
2017/3/28         3.820896  1.791045  0.044776  0.014925       54        0   
2017/3/29         2.800000  1.653846  0.053846  0.015385      104        0   
2017/3/30         3.596774  1.725806  0.040323  0.024194       85        0   
2017/3/31         3.084615  1.846154  0.069231  0.000000       98        0   

              ...  wait_less_than_3  wait_between_3_30  wait_greater_than_30  \
arrival_date  ...                                                              
2015/7/1      ...               103                  0                     0   
2015/7/2      ...                36                  0                     0   
2015/7/3      ...                37                  0                     0   
2015/7/4      ...                45                  0                     0   
2015/7/5      ...                37                  0                     0   
...           ...               ...                ...                   ...   
2017/3/27     ...               114                  0                     0   
2017/3/28     ...                67                  0                     0   
2017/3/29     ...               130                  0                     0   
2017/3/30     ...               124                  0                     0   
2017/3/31     ...               130                  0                     0   

              contract  group  transient  transient_party  \
arrival_date                                                
2015/7/1             6      0         97                0   
2015/7/2            13      0         20                3   
2015/7/3             6      0         22                9   
2015/7/4             7      0         26               12   
2015/7/5             9      1         27                0   
...                ...    ...        ...              ...   
2017/3/27            0      2         67               45   
2017/3/28            0      1         64                2   
2017/3/29            0      3        125                2   
2017/3/30            3      0        102               19   
2017/3/31            4      1        123                2   

              mean_required_car_parking_space  special_requests_ratio  quatity  
arrival_date                              

In [3]:
y_label=pd.read_csv('train_label.csv', engine='python',index_col="arrival_date")
# test_nolabel = pd.read_csv('test_nolabel.csv', engine='python')

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
tree = DecisionTreeClassifier(max_depth=)
scores = cross_val_score(tree,train,y_label,cv=5,scoring='f1_micro')
print(scores)
print(scores.mean())

[0.3125    0.4921875 0.3515625 0.421875  0.484375 ]
0.4125


In [26]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=150,max_depth=10, random_state=0)
# scores = cross_val_score(rf,train,y_label,cv=5,scoring='neg_mean_absolute_error')
scores = cross_val_score(rf,train,y_label,cv=5,scoring='f1_micro')
print(scores)
print(scores.mean())

[0.3046875 0.6328125 0.6015625 0.578125  0.546875 ]
0.5328125


In [59]:
from sklearn.ensemble import AdaBoostClassifier
ab=AdaBoostClassifier()
# scores = cross_val_score(ab,train,y_label,cv=5,scoring='neg_mean_absolute_error')
scores = cross_val_score(ab,train,y_label,cv=5,scoring='f1_micro')
print(scores)
print(scores.mean())

[0.2890625 0.3515625 0.359375  0.3671875 0.359375 ]
0.3453125


In [27]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=200)
# scores = cross_val_score(gb,train,y_label,cv=5,scoring='neg_mean_absolute_error')
scores = cross_val_score(gb,train,y_label,cv=5,scoring='f1_micro')
print(scores)
print(scores.mean())

[0.328125  0.578125  0.53125   0.5546875 0.4453125]
0.4875


In [61]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()
# scores = cross_val_score(lg,train,y_label,cv=5,scoring='neg_mean_absolute_error')
scores = cross_val_score(lg,train,y_label,cv=5,scoring='f1_micro')
print(scores)
print(scores.mean())

[0.3125    0.421875  0.4140625 0.2734375 0.3828125]
0.3609375


In [62]:
from sklearn import svm
s = svm.SVC()
# scores = cross_val_score(s,train,y_label,cv=5,scoring='neg_mean_absolute_error')
scores = cross_val_score(s,train,y_label,cv=5,scoring='f1_micro')
print(scores)
print(scores.mean())

[0.2890625 0.5546875 0.5234375 0.5703125 0.5625   ]
0.5


In [50]:
import numpy as np
train_lstm=np.array(train)
X_train_all = np.reshape(train_lstm, (train_lstm.shape[0], 1, train_lstm.shape[1]))
y_label_tr=pd.get_dummies(y_label, columns=["label"])

In [48]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten,LSTM,Embedding
from keras import optimizers
from keras.callbacks import EarlyStopping

In [68]:
from keras import backend as K
def recall_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    recall = true_positives / (possible_positives + K.epsilon())
    return recall

def precision_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    return precision
def f1_m(y_true, y_pred):
    precision = precision_m(y_true, y_pred)
    recall = recall_m(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [119]:
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split,KFold,cross_val_score
from sklearn.metrics import classification_report,confusion_matrix
kfold=KFold(5,True,0)
cvscores = []
cvscores_f1 = []
for train1, test1 in kfold.split(train,y_label):
#     print(train1)
    X_train=np.array(train.iloc[train1])
    X_test=np.array(train.iloc[test1])
    y_train=y_label_tr.iloc[train1]
    y_test=y_label_tr.iloc[test1]
#     X_train, X_test, y_train, y_test = train_test_split(train_lstm, y_label_tr, test_size = 0.2, random_state = 0)
    X_train = np.reshape(X_train, (X_train.shape[0], 1, X_train.shape[1]))
    X_test = np.reshape(X_test,(X_test.shape[0], 1, X_test.shape[1]))
#     print(y_train)

    model = Sequential()

#     model.add(LSTM(units = 256, input_dim=42))
    model.add(LSTM(units = 256, input_dim=42,return_sequences=True))
    model.add(LSTM(128,return_sequences=True))#new
    model.add(LSTM(64))#new
    model.add(Dropout(0.2))
    model.add(Dense(32))
#     model.add(Dropout(0.25))
#     model.add(Dense(16))
    model.add(Dense(10, activation='sigmoid'))
    model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['mae',f1_m,'accuracy'])
    model.fit(X_train, y_train, batch_size=20, epochs=40, verbose=0)
#     scores = model.evaluate(X_test, y_test, verbose=0)
# #     print("%s: %.2f%%" % (model.metrics_names[1], scores[1]))
#     cvscores.append(scores[1] * 100)
    

    y_pred = model.predict(X_test, batch_size=64, verbose=0)
    y_pred_bool = np.argmax(y_pred, axis=1)
    y_test_bool = np.argmax(np.array(y_test), axis=1)
    print(classification_report(y_test_bool, y_pred_bool))
    print(confusion_matrix(y_test_bool, y_pred_bool))
# print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores), np.std(cvscores)))

              precision    recall  f1-score   support

           0       1.00      0.82      0.90        17
           1       0.70      0.53      0.60        30
           2       0.55      0.54      0.55        39
           3       0.38      0.83      0.52        24
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         3

    accuracy                           0.55       128
   macro avg       0.38      0.39      0.37       128
weighted avg       0.53      0.55      0.53       128

[[14  3  0  0  0  0  0]
 [ 0 16 13  1  0  0  0]
 [ 0  4 21 14  0  0  0]
 [ 0  0  4 20  0  0  0]
 [ 0  0  0  9  0  0  0]
 [ 0  0  0  6  0  0  0]
 [ 0  0  0  3  0  0  0]]
              precision    recall  f1-score   support

           0       0.86      0.71      0.77        17
           1       0.66      0.68      0.67        34
           2       0.60      0.45      0.51        40
           3     

In [78]:
cvscores

[12.045516073703766,
 12.159467488527298,
 12.27007657289505,
 12.669649720191956,
 11.850880086421967]

In [79]:
cvscores_f1

[30.316171050071716,
 21.471290290355682,
 30.50958812236786,
 31.440362334251404,
 35.180214047431946]

In [118]:
train_lstm=np.array(train)
X_train = np.reshape(train_lstm, (train_lstm.shape[0], 1, train_lstm.shape[1]))
model = Sequential()
#     model.add(LSTM(units = 256, input_dim=42))
model.add(LSTM(units = 256, input_dim=42,return_sequences=True))
model.add(LSTM(128,return_sequences=True))#new
model.add(LSTM(64))#new
model.add(Dropout(0.2))
model.add(Dense(32))
#     model.add(Dropout(0.25))
#     model.add(Dense(16))
model.add(Dense(10, activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['mae',f1_m,'accuracy'])
model.fit(X_train, y_label_tr, batch_size=20, epochs=40, verbose=0)
#     scores = model.evaluate(X_test, y_test, verbose=0)
# #     print("%s: %.2f%%" % (model.metrics_names[1], scores[1]))
#     cvscores.append(scores[1] * 100)
    

y_pred_train = model.predict(X_train, batch_size=64, verbose=0)
y_pred_bool_train = np.argmax(y_pred_train, axis=1)
y_train_bool = np.argmax(np.array(y_label_tr), axis=1)
print(classification_report(y_train_bool, y_pred_bool_train))
print(confusion_matrix(y_train_bool, y_pred_bool_train))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89        94
           1       0.79      0.68      0.73       152
           2       0.72      0.68      0.70       186
           3       0.47      0.85      0.61       124
           4       0.00      0.00      0.00        46
           5       0.00      0.00      0.00        21
           6       0.00      0.00      0.00        13
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         2
           9       0.00      0.00      0.00         1

    accuracy                           0.67       640
   macro avg       0.28      0.32      0.29       640
weighted avg       0.61      0.67      0.63       640

[[ 90   4   0   0   0   0   0   0   0   0]
 [ 17 104  29   2   0   0   0   0   0   0]
 [  0  23 126  37   0   0   0   0   0   0]
 [  1   0  17 106   0   0   0   0   0   0]
 [  0   0   2  44   0   0   0   0   0   0]
 [  0   0   0  21   0   0 

In [37]:
import numpy as np
train_lstm=np.array(train)
X_train = np.reshape(train_lstm, (train_lstm.shape[0], 1, train_lstm.shape[1]))
test_lstm=np.array(test)
X_test = np.reshape(test_lstm, (test_lstm.shape[0], 1, test_lstm.shape[1]))
y_label_tr=pd.get_dummies(y_label, columns=["label"])

NameError: name 'test' is not defined

In [71]:
import xgboost as xgb

ModuleNotFoundError: No module named 'xgboost'

In [52]:
import xgboost as xgb
dtrain = xgb.DMatrix(train, label=y_label)
param = {'max_depth': 2, 'eta': 1, 'objective': 'binary:logistic'}
param['nthread'] = 4
param['eval_metric'] = 'auc'
bst = xgb.train(param, dtrain, num_round, evallist)
ypred = bst.predict(test, ntree_limit=bst.best_ntree_limit)

XGBoostError: XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libomp.dylib for Mac OSX, libgomp.so for Linux and other UNIX-like OSes). Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
  * You are running 32-bit Python on a 64-bit OS
Error message(s): ['dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: image not found']
