In [1]:
import numpy as np
import pandas as pd
import calendar
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report,confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten,LSTM,Embedding
from keras import optimizers
from keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [2]:
# preprocess=pd.read_csv('preprocess.csv', engine='python',index_col="arrival_date")
train=pd.read_csv('preprocess_all/preprocess_train_per_all.csv', engine='python',index_col="arrival_date")
# train=train.drop(["label"],axis=1)
train

hotel_Resort  hotel_City   lead_time  arrival_date_week_number  \
arrival_date                                                                   
2015/7/1          0.368932    0.631068  190.291262                        27   
2015/7/2          0.972222    0.027778   69.944444                        27   
2015/7/3          0.729730    0.270270   65.378378                        27   
2015/7/4          0.800000    0.200000  120.777778                        27   
2015/7/5          1.000000    0.000000   75.378378                        28   
...                    ...         ...         ...                       ...   
2017/3/27         0.219298    0.780702   96.368421                        13   
2017/3/28         0.492537    0.507463   52.537313                        13   
2017/3/29         0.392308    0.607692   41.130769                        13   
2017/3/30         0.411290    0.588710   59.137097                        13   
2017/3/31         0.457143    0.542857   58.053846                        13   

              stays_nights    adults  children    babies   meal_BB   meal_FB  \
arrival_date                                                                   
2015/7/1          3.048544  1.805825  0.019417  0.000000  0.339806  0.009709   
2015/7/2          5.694444  1.972222  0.055556  0.000000  0.750000  0.027778   
2015/7/3          4.324324  2.000000  0.081081  0.000000  0.594595  0.000000   
2015/7/4          5.311111  1.977778  0.111111  0.044444  0.822222  0.022222   
2015/7/5          6.108108  1.945946  0.216216  0.000000  0.702703  0.000000   
...                    ...       ...       ...       ...       ...       ...   
2017/3/27         2.982456  1.842105  0.000000  0.000000  0.868421  0.000000   
2017/3/28         3.820896  1.791045  0.044776  0.014925  0.805970  0.000000   
2017/3/29         2.800000  1.653846  0.053846  0.015385  0.800000  0.000000   
2017/3/30         3.596774  1.725806  0.040323  0.024194  0.685484  0.000000   
2017/3/31         3.084615  1.846154  0.069231  0.000000  0.753846  0.000000   

              ...  wait_less_than_3  wait_between_3_30  wait_greater_than_30  \
arrival_date  ...                                                              
2015/7/1      ...               1.0                0.0                   0.0   
2015/7/2      ...               1.0                0.0                   0.0   
2015/7/3      ...               1.0                0.0                   0.0   
2015/7/4      ...               1.0                0.0                   0.0   
2015/7/5      ...               1.0                0.0                   0.0   
...           ...               ...                ...                   ...   
2017/3/27     ...               1.0                0.0                   0.0   
2017/3/28     ...               1.0                0.0                   0.0   
2017/3/29     ...               1.0                0.0                   0.0   
2017/3/30     ...               1.0                0.0                   0.0   
2017/3/31     ...               1.0                0.0                   0.0   

              contract     group  transient  transient_party  \
arrival_date                                                   
2015/7/1      0.058252  0.000000   0.941748         0.000000   
2015/7/2      0.361111  0.000000   0.555556         0.083333   
2015/7/3      0.162162  0.000000   0.594595         0.243243   
2015/7/4      0.155556  0.000000   0.577778         0.266667   
2015/7/5      0.243243  0.027027   0.729730         0.000000   
...                ...       ...        ...              ...   
2017/3/27     0.000000  0.017544   0.587719         0.394737   
2017/3/28     0.000000  0.014925   0.955224         0.029851   
2017/3/29     0.000000  0.023077   0.961538         0.015385   
2017/3/30     0.024194  0.000000   0.822581         0.153226   
2017/3/31     0.030769  0.007692   0.946154         0.015385   

              mean_required_car_parking_space  special_req

In [3]:
y_label=pd.read_csv('train_label.csv', engine='python',index_col="arrival_date")
# test_nolabel = pd.read_csv('test_nolabel.csv', engine='python')
y_label_tr=pd.get_dummies(y_label, columns=["label"])
y_label_tr

label_0.0  label_1.0  label_2.0  label_3.0  label_4.0  \
arrival_date                                                          
2015-07-01            0          0          1          0          0   
2015-07-02            0          1          0          0          0   
2015-07-03            0          1          0          0          0   
2015-07-04            0          1          0          0          0   
2015-07-05            0          1          0          0          0   
...                 ...        ...        ...        ...        ...   
2017-03-27            0          0          1          0          0   
2017-03-28            0          1          0          0          0   
2017-03-29            0          0          1          0          0   
2017-03-30            0          0          0          1          0   
2017-03-31            0          0          0          1          0   

              label_5.0  label_6.0  label_7.0  label_8.0  label_9.0  
arrival_date                                                         
2015-07-01            0          0          0          0          0  
2015-07-02            0          0          0          0          0  
2015-07-03            0          0          0          0          0  
2015-07-04            0          0          0          0          0  
2015-07-05            0          0          0          0          0  
...                 ...        ...        ...        ...        ...  
2017-03-27            0          0          0          0          0  
2017-03-28            0          0          0          0          0  
2017-03-29            0          0          0          0          0  
2017-03-30            0          0          0          0          0  
2017-03-31            0          0          0          0          0  

[640 rows x 10 columns]

In [4]:
# preprocess=pd.read_csv('preprocess.csv', engine='python',index_col="arrival_date")
test=pd.read_csv('preprocess_all/preprocess_test_per_all.csv', engine='python',index_col="arrival_date")
# train=train.drop(["label"],axis=1)
test

hotel_Resort  hotel_City   lead_time  arrival_date_week_number  \
arrival_date                                                                   
2017/4/1          0.265152    0.734848   95.265152                        13   
2017/4/2          0.302083    0.697917   73.364583                        14   
2017/4/3          0.277056    0.722944   76.995671                        14   
2017/4/4          0.224000    0.776000  104.544000                        14   
2017/4/5          0.361111    0.638889  119.769841                        14   
...                    ...         ...         ...                       ...   
2017/8/27         0.385057    0.614943   93.954023                        35   
2017/8/28         0.369668    0.630332  139.222749                        35   
2017/8/29         0.280000    0.720000  141.672000                        35   
2017/8/30         0.471910    0.528090   98.303371                        35   
2017/8/31         0.410448    0.589552  110.888060                        35   

              stays_nights    adults  children    babies   meal_BB   meal_FB  \
arrival_date                                                                   
2017/4/1          3.969697  2.068182  0.151515  0.007576  0.803030  0.000000   
2017/4/2          3.822917  1.947917  0.083333  0.010417  0.760417  0.000000   
2017/4/3          3.307359  1.761905  0.082251  0.004329  0.878788  0.000000   
2017/4/4          3.048000  1.912000  0.152000  0.000000  0.888000  0.000000   
2017/4/5          3.484127  1.702381  0.051587  0.000000  0.920635  0.000000   
...                    ...       ...       ...       ...       ...       ...   
2017/8/27         3.178161  1.948276  0.258621  0.000000  0.660920  0.011494   
2017/8/28         4.374408  1.696682  0.151659  0.004739  0.478673  0.014218   
2017/8/29         3.888000  1.816000  0.168000  0.000000  0.744000  0.000000   
2017/8/30         3.921348  1.955056  0.213483  0.011236  0.775281  0.000000   
2017/8/31         3.955224  2.044776  0.141791  0.000000  0.708955  0.000000   

              ...  wait_less_than_3  wait_between_3_30  wait_greater_than_30  \
arrival_date  ...                                                              
2017/4/1      ...          0.977273           0.000000              0.022727   
2017/4/2      ...          0.989583           0.000000              0.010417   
2017/4/3      ...          0.991342           0.000000              0.008658   
2017/4/4      ...          0.984000           0.016000              0.000000   
2017/4/5      ...          0.980159           0.003968              0.015873   
...           ...               ...                ...                   ...   
2017/8/27     ...          1.000000           0.000000              0.000000   
2017/8/28     ...          1.000000           0.000000              0.000000   
2017/8/29     ...          1.000000           0.000000              0.000000   
2017/8/30     ...          1.000000           0.000000              0.000000   
2017/8/31     ...          1.000000           0.000000              0.000000   

              contract     group  transient  transient_party  \
arrival_date                                                   
2017/4/1      0.007576  0.000000   0.803030         0.189394   
2017/4/2      0.041667  0.000000   0.916667         0.041667   
2017/4/3      0.017316  0.012987   0.757576         0.212121   
2017/4/4      0.000000  0.000000   0.888000         0.112000   
2017/4/5      0.003968  0.000000   0.527778         0.468254   
...                ...       ...        ...              ...   
2017/8/27     0.017241  0.011494   0.867816         0.103448   
2017/8/28     0.018957  0.009479   0.630332         0.341232   
2017/8/29     0.016000  0.016000   0.952000         0.016000   
2017/8/30     0.000000  0.044944   0.932584         0.022472   
2017/8/31     0.059701  0.007463   0.835821         0.097015   

              mean_required_car_parking_space  special_req

In [5]:
y_test_label=pd.read_csv('test_nolabel.csv', engine='python')
# test_nolabel = pd.read_csv('test_nolabel.csv', engine='python')
# y_label_tr=pd.get_dummies(y_label, columns=["label"])
y_test_label

arrival_date
0     2017-04-01
1     2017-04-02
2     2017-04-03
3     2017-04-04
4     2017-04-05
..           ...
148   2017-08-27
149   2017-08-28
150   2017-08-29
151   2017-08-30
152   2017-08-31

[153 rows x 1 columns]

In [6]:
train_lstm=np.array(train)
# train_lstm=train.drop(["arrival_date"],axis=1)
train_lstm=np.array(train_lstm)
X_train = np.reshape(train_lstm, (train_lstm.shape[0], 1, train_lstm.shape[1]))
X_train, X_test, y_train, y_test = train_test_split(X_train, y_label_tr, test_size=0.2, random_state=42)
model = Sequential()
#     model.add(LSTM(units = 256, input_dim=42))
model.add(LSTM(units = 256, input_dim=42))
# model.add(LSTM(128))#new
# model.add(LSTM(64))#new
# model.add(Dropout(0.2))
model.add(Dense(128, activation='relu'))
#     model.add(Dropout(0.25))
#     model.add(Dense(16))
model.add(Dense(10, activation='sigmoid'))
callback = EarlyStopping(monitor="val_loss", patience=20, verbose=1, mode="auto")
model.compile(loss='binary_crossentropy',optimizer='adam')
model.fit(X_train, y_train, batch_size=200, epochs=1000, verbose=0,callbacks=[callback])
#     scores = model.evaluate(X_test, y_test, verbose=0)
# #     print("%s: %.2f%%" % (model.metrics_names[1], scores[1]))
#     cvscores.append(scores[1] * 100)

y_pred_train = model.predict(X_test, batch_size=64, verbose=0)
y_pred_bool_test = np.argmax(y_pred_train, axis=1)
y_test_bool = np.argmax(np.array(y_test), axis=1)
print(classification_report(y_test_bool, y_pred_bool_test))
print(confusion_matrix(y_test_bool, y_pred_bool_test))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

              precision    recall  f1-score   support

           0       0.94      0.75      0.83        20
           1       0.76      0.90      0.82        31
           2       0.80      0.71      0.75        34
           3       0.67      0.74      0.70        27
           4       0.33      0.20      0.25        10
           5       0.29      0.67      0.40         3
           6       0.00      0.00      0.00         2
           9       0.00      0.00      0.00         1

    accuracy                           0.71       128
   macro avg       0.47      0.50      0.47       128
weighted avg       0.72      0.71      0.71       128

[[15  5  0  0  0  0  0  0]
 [ 1 28  1  1  0  0  0  0]
 [ 0  4 24  5  1  0  0  0]
 [ 0  0  4 20  2  1  0  0]
 [ 0  0  1  3  2  3  1  0]
 [ 0  0  0  1  0  2  0  0]
 [ 0  0  0 

In [7]:
error = []
for i in range(len(y_test_bool)):
    error.append(y_test_bool[i] - y_pred_bool_test[i])

# print("Errors: ", error)
# print(error)

absError = []
for val in error:
    absError.append(abs(val))#誤差絕對值

# print("Absolute Value of Error: ", absError)
from math import sqrt
print("MAE = ", sum(absError) / len(absError))#平均絕對誤差MAE
 

MAE =  0.359375


In [8]:
train_lstm=np.array(train)
# train_lstm=train.drop(["arrival_date"],axis=1)
# train_lstm=np.array(train_lstm)
X_train = np.reshape(train_lstm, (train_lstm.shape[0], 1, train_lstm.shape[1]))
# X_train, X_test, y_train, y_test = train_test_split(X_train, y_label_tr, test_size=0.2, random_state=42)
model = Sequential()
#     model.add(LSTM(units = 256, input_dim=42))
model.add(LSTM(units = 256, input_dim=42))
# model.add(LSTM(128))#new
# model.add(LSTM(64))#new
# model.add(Dropout(0.2))
model.add(Dense(128, activation='relu'))
#     model.add(Dropout(0.25))
#     model.add(Dense(16))
model.add(Dense(10, activation='sigmoid'))
callback = EarlyStopping(monitor="val_loss", patience=20, verbose=1, mode="auto")
model.compile(loss='binary_crossentropy',optimizer='adam')
model.fit(X_train, y_label_tr, batch_size=200, epochs=1000, verbose=0,callbacks=[callback])
#     scores = model.evaluate(X_test, y_test, verbose=0)
# #     print("%s: %.2f%%" % (model.metrics_names[1], scores[1]))
#     cvscores.append(scores[1] * 100)

y_pred_train = model.predict(X_train, batch_size=64, verbose=0)
y_pred_bool_train = np.argmax(y_pred_train, axis=1)
y_train_bool = np.argmax(np.array(y_label_tr), axis=1)
print(classification_report(y_train_bool, y_pred_bool_train))
print(confusion_matrix(y_train_bool, y_pred_bool_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        94
           1       1.00      1.00      1.00       152
           2       0.98      1.00      0.99       186
           3       0.99      0.97      0.98       124
           4       0.94      0.98      0.96        46
           5       1.00      0.90      0.95        21
           6       1.00      1.00      1.00        13
           7       1.00      1.00      1.00         1
           8       1.00      1.00      1.00         2
           9       1.00      1.00      1.00         1

    accuracy                           0.99       640
   macro avg       0.99      0.99      0.99       640
weighted avg       0.99      0.99      0.99       640

[[ 94   0   0   0   0   0   0   0   0   0]
 [  0 152   0   0   0   0   0   0   0   0]
 [  0   0 186   0   0   0   0   0   0   0]
 [  0   0   3 120   1   0   0   0   0   0]
 [  0   0   0   1  45   0   0   0   0   0]
 [  0   0   0   0   2  19 

In [9]:
test_lstm=np.array(test)
X_test = np.reshape(test_lstm, (test_lstm.shape[0], 1, test_lstm.shape[1]))
y_pred_test = model.predict(X_test, batch_size=64, verbose=0)
y_pred_bool_test = np.argmax(y_pred_test, axis=1)
y_pred_bool_test=pd.DataFrame(y_pred_bool_test,columns=["label"])
y_test_num=pd.concat([y_test_label,y_pred_bool_test],axis=1)

In [10]:
y_test_num

arrival_date  label
0     2017-04-01      3
1     2017-04-02      2
2     2017-04-03      6
3     2017-04-04      3
4     2017-04-05      4
..           ...    ...
148   2017-08-27      6
149   2017-08-28      6
150   2017-08-29      4
151   2017-08-30      3
152   2017-08-31      3

[153 rows x 2 columns]

In [11]:
import csv

# 開啟輸出的 CSV 檔案
with open('model_predict/lstm_per.csv', 'w', newline='') as csvfile:
    # 建立 CSV 檔寫入器
    writer = csv.writer(csvfile)

    # 寫入標題資料
    writer.writerow(["arrival_date","label"])
    # 寫入距離資料
    for i in range(len(y_test_num)):
        writer.writerow([y_test_num["arrival_date"].iloc[i],y_test_num["label"].iloc[i]])
        

In [12]:
y_test_num.groupby("label").count()

arrival_date
label              
2                 3
3                38
4                23
5                 3
6                64
8                22

In [13]:
y_label_full=pd.read_csv('train_label.csv', engine='python')

In [14]:
y_label_full.groupby("label").count()

arrival_date
label              
0.0              94
1.0             152
2.0             186
3.0             124
4.0              46
5.0              21
6.0              13
7.0               1
8.0               2
9.0               1