In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
import seaborn as sns; sns.set()

In [5]:
# 導入關鍵詞向量
keyword_vector = pd.read_csv('training_X_binary_2%_700.csv',index_col = 0)
#keyword_vector = pd.read_csv('training_X_times_開根號.csv',index_col = 0)
print(keyword_vector.values)

header = list(keyword_vector.columns.values)
# print(keyword_vector.info)
# print(header)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
# 定義好資料向量內容
X = keyword_vector.values
print('X:',X)


# 定義好目標名稱: 看漲/看跌
name = ["POS", "NEG"]
target_name = np.array(name)
print('target_name:',target_name)

# 導入文章漲跌篇數
real_updown = pd.read_csv('training_Y_2%_700.csv')
target_list = []

for i in range(len(real_updown.values)):  # 總共3183篇
    num = int(real_updown.values[i][0])
    target_list.append(num)

y = np.array(target_list)
print('y:',y)
print(real_updown)

X: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
target_name: ['POS' 'NEG']
y: [ 1  1  1 ... -1 -1 -1]
      y
0     1
1     1
2     1
3     1
4     1
...  ..
3178 -1
3179 -1
3180 -1
3181 -1
3182 -1

[3183 rows x 1 columns]


In [111]:
from sklearn.metrics import confusion_matrix

# 跑迴圈數次，看最大可以跑多少
Training_Set_Score = []
Test_Set_Score = []
Confusion_Matrix = []
max_training_set_score = float()
max_test_set_score = float()
max_confusion_matrix = []

for i in range(100):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)  # 套件功能把資料打散分為訓練集跟測試集
    
    # 多項氏貝式分類器 Multinomial Naive Bayes
    modelm=MultinomialNB()  # alpha預設為1
    modelm.fit(X_train,y_train)  # 資料集餵入模型
    labels=modelm.predict(X_test)  # 看測試集分類結果
        
    # 記錄每次的結果,可以print出來看
    #Training_Set_Score.append(modelm.score(X_train,y_train))
    #Test_Set_Score.append(modelm.score(X_test,y_test))
    #Confusion_Matrix.append(confusion_matrix(y_test, labels))
    
    test_set_score = modelm.score(X_test,y_test)
    if test_set_score > max_test_set_score:
        max_test_set_score = test_set_score
        max_training_set_score = modelm.score(X_train,y_train)
        max_confusion_matrix = confusion_matrix(y_test, labels)
    

#print(Training_Set_Score)
#print(Test_Set_Score)
#print(Confusion_Matrix)

print('max_training_set_score:',max_training_set_score)
print('max_test_set_score:',max_test_set_score)
print(max_confusion_matrix)

max_training_set_score: 0.7545168892380204
max_test_set_score: 0.7582417582417582
[[233  82]
 [ 72 250]]


In [10]:
# X是每篇文章的關鍵詞向量, y是每篇文章的實際漲跌
# X_train第1~5月文章關鍵詞, X_test第6月文章關鍵詞, y_train第1~5月文章實際漲跌, y_test第6月文章實際漲跌

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)  # 套件功能把資料打散分為訓練集跟測試集

# 多項氏貝式分類器 Multinomial Naive Bayes
modelm=MultinomialNB()  # alpha預設為1
modelm.fit(X_train,y_train)  # 資料集餵入模型
labels=modelm.predict(X_test)  # 看測試集分類結果

print(y_train)

[ 1 -1  1 ... -1 -1  1]


In [8]:
print('Training Set Score:',modelm.score(X_train,y_train))  # 訓練集成效
print('Test Set Score:',modelm.score(X_test,y_test))  # 測試集成效

Training Set Score: 0.7647289866457188
Test Set Score: 0.7142857142857143


In [114]:
print(confusion_matrix(y_test, labels))

[[202 103]
 [ 86 246]]


In [ ]:
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test, labels)
sns.heatmap(mat.T, square=True, annot=True, fmt='d', cbar=False,
            xticklabels=target_name, yticklabels=target_name)
plt.xlabel('true label')
plt.ylabel('predicted label')

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, labels))